### ISSUE TITLE
Add wdk compilation environment support

### ISSUE THREAD

**Issue by ranwei1025** [tboox/xmake#159]
#### References

* [Enterprise WDK for Windows 10](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* [Windows-driver-samples](https://github.com/Microsoft/Windows-driver-samples)
* [Make .cab driver package and release sign](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release)
* [How to do test sign](https://blog.csdn.net/anda0109/article/details/49473915)

#### Tests

Please download [xmake-v2.2.1-dev](https://github.com/tboox/xmake/releases/download/v2.1.9/xmake-v2.2.1-dev.exe) and try it.

#### Online Docs

[https://xmake.io/#/home?id=wdk-driver-program](https://xmake.io/#/home?id=wdk-driver-program)

#### Roadmap

- [x] detect.sdks.find_wdk
  - [x] wdk 10.0
- [x] target rules (need be applied to target in xmake.lua)
  - [x] rule("wdk.driver")
  - [x] rule("wdk.binary")
  - [x] rule("wdk.static")
  - [x] rule("wdk.shared")
  - [x] rule("wdk.env.kmdf")
  - [x] rule("wdk.env.umdf")
  - [x] rule("wdk.env.wdm")
- [x] config values
    - [x] set_values("wdk.umdf.sdkver", "1.9")
    - [x] set_values("wdk.kmdf.sdkver", "2.15")
    - [x] set_values("wdk.inf2cat.os", ...) 
    - [x] set_values("wdk.env.winver", "8.1" or "8" or "7")
      - default: "10" 
- [x] [wdk-tasks-for-msbuild](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/wdk-tasks-for-msbuild)
  - [x] rule("wdk.inf") 
    - [x] add_values("wdk.inf.flags", ...) 
  - [x] rule("wdk.tracewpp")
    - [x] add_values("wdk.tracewpp.flags", ...) 
  - [x] rule("wdk.man")
    - [x] add_values("wdk.man.flags", ...) 
    - [x] add_values("wdk.man.prefix", ...) 
    - [x] add_values("wdk.man.header", ...) 
    - [x] add_values("wdk.man.counter_header", ...) 
    - [x] add_values("wdk.man.resource", ...) 
  - [x] rule("wdk.mc")
    - [x] add_values("wdk.mc.flags", ...) 
    - [x] add_values("wdk.mc.header", ...) 
  - [x] rule("wdk.mof")
    - [x] add_values("wdk.mof.flags", ...) 
    - [x] add_values("wdk.mof.header", ...) 
  - [x] rule("wdk.sign")
    - [x] set_values("wdk.sign.mode", "test" or "release")  
      - default: no signing
    - [x] set_values("wdk.sign.store", ...)  
    - [x] set_values("wdk.sign.thumbprint", "032122545DCAA6167B1ADBE5F7FDF07AE2234AAA")  
    - [x] set_values("wdk.sign.company", ...)  
    - [x] set_values("wdk.sign.certfile", "signcert.cer")  
    - [x] set_values("wdk.sign.timestamp", "http://timestamp.verisign.com/scripts/timstamp.dll") 
      - optional
  - [x] rule("wdk.package.cab")
     - `xmake package`

**Comment by waruqi** [comment]
umdf example [echo](https://github.com/tboox/xmake/tree/master/tests/projects/wdk/umdf/echo): 

```lua

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- enable unicode
add_defines("_UNICODE", "UNICODE")

-- add target
target("echo")

    -- add rules
    add_rules("wdk.umdf.driver")

    -- add files
    add_files("driver/*.c") 
    add_files("driver/*.inx")

    -- add includedirs
    add_includedirs("exe")

-- add target
target("app")

    -- add rules
    add_rules("wdk.umdf.binary")

    -- add files
    add_files("exe/*.cpp") 
```

**Comment by waruqi** [comment]
kmdf example [ioctl](https://github.com/tboox/xmake/tree/master/tests/projects/wdk/kmdf/ioctl):

```lua
-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- add target
target("nonpnp")

    -- add rules
    add_rules("wdk.kmdf.driver")

    -- add files
    add_files("driver/*.c", {rule = "wdk.tracewpp"}) 

-- add target
target("app")

    -- add deps
    add_deps("nonpnp")

    -- add rules
    add_rules("wdk.kmdf.binary")

    -- add files
    add_files("exe/*.c") 
    add_files("exe/*.inf")
```

**Comment by waruqi** [comment]
kmdf example with *.man [ioctl](https://github.com/tboox/xmake/tree/master/tests/projects/wdk/kmdf/kcs):

```lua
-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- add target
target("kcs")

    -- add rules
    add_rules("wdk.kmdf.driver")

    -- add flags for rule: wdk.man
    add_values("wdk.man.flags", "-prefix Kcs")
    add_values("wdk.man.resource", "kcsCounters.rc")
    add_values("wdk.man.header", "kcsCounters.h")
    add_values("wdk.man.counter_header", "kcsCounters_counters.h")
    
    -- add files
    add_files("*.c", "*.rc", "*.man") 
```

**Comment by waruqi** [comment]
kmdf example with *.mc [serial](https://github.com/tboox/xmake/tree/master/tests/projects/wdk/kmdf/serial):

```lua
-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- add target
target("serial")

    -- add rules
    add_rules("wdk.kmdf.driver")

    -- add flags for rule: wdk.tracewpp
    add_values("wdk.tracewpp.flags", "-func:SerialDbgPrintEx(LEVEL,FLAGS,MSG,...)")

    -- add header file name for rule: wdk.mc
    add_values("wdk.mc.header", "serlog.h")

    -- add files
    add_files("*.c", {rule = "wdk.tracewpp"}) 
    add_files("*.mc", "*.rc", "*.inx")
```

**Comment by waruqi** [comment]
kmdf example with *.mof [msdsm](https://github.com/tboox/xmake/tree/master/tests/projects/wdk/kmdf/msdsm):

```lua

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- add target
target("msdsm")

    -- add rules
    add_rules("wdk.kmdf.driver")

    -- add flags for rule: wdk.tracewpp
    add_values("wdk.tracewpp.flags", "-func:TracePrint((LEVEL,FLAGS,MSG,...))")

    -- add files
    add_files("*.c", {rule = "wdk.tracewpp"}) 
    add_files("*.rc", "*.inf")
    add_files("*.mof|msdsm.mof")

    -- add file msdsm.mof and modify default wdk.mof.header for this file
    add_files("msdsm.mof", {values = {wdk_mof_header = "msdsmwmi.h"}}) 

    -- set precompiled header
    set_pcheader("precomp.h")

    -- add links
    add_links("mpio")
```

**Comment by ranwei1025** [comment]
1、需要增加指定wdk安装路径 对于当前cmd已经存在wdk环境变量的情况 直接使用
2、需要增加wdk.wdm.driver规则 比如测试例子的 perfcounters 就是wdm程序 就不应该按照kmdf规则处理
3、需要增加编译应用程序规则 比如 wdk例子下usbview 编译支持

**Comment by ranwei1025** [comment]
usbview 是个图形界面应用程序 但不依赖于umdf 
应该增加 如wdk的 winxp win7 win2003 等编译环境设置 这个对驱动编译是比较有用的

**Comment by waruqi** [comment]
Ok, I will modify rules. 

Thanks!

**Comment by waruqi** [comment]
I add `win.sdk.application` and `win.sdk.dotnet` rules to compile [usbview](https://github.com/tboox/xmake/tree/master/tests/projects/winsdk/usbview) example, you can see [#173](https://github.com/tboox/xmake/issues/173)

**Comment by waruqi** [comment]
Uses the other given wdk directory (mount EWDK_rs3_release_svc_16299_171024-1647.iso to G:\):

```console
$ xmake f --wdk="G:\Program Files\Windows Kits\10" -c
$ xmake
```

**Comment by waruqi** [comment]
Package driver and make *.cab file to build or the given output directory:

```console
$ xmake [p|package]
$ xmake [p|package] -o outputdir
```

```
build directory
  - drivers
    - sampledsm
       - debug/x86/sampledsm.cab
       - release/x64/sampledsm.cab
       - debug/x86/sampledsm.cab
       - release/x64/sampledsm.cab
```

**Comment by waruqi** [comment]
Compile driver target for low version windows (default: win10):

```lua
-- for win8.1
set_values("wdk.env.winver", "8.1")

-- for win8
set_values("wdk.env.winver", "8")

-- for win7
set_values("wdk.env.winver", "7")
```

**Comment by waruqi** [comment]
See [Online docs about WDK program](https://xmake.io/#/home?id=wdk-driver-program)
